export const MONTHLY_QUOTES = [
  {
    month: 0,
    chapter: "Chapter – 1 · Discipline (Starting Strong)",
    quote: "Discipline is choosing between what you want now and what you want most.",
    author: "Abraham Lincoln",
    message: "Strong beginnings create strong identities. Show up daily, even when it feels small.",
    gradient: "linear-gradient(135deg, #ecfdf5, #d1fae5)",
    colors: {
      chapter: "#065f46",
      quote: "#064e3b",
      author: "#047857",
      message: "#065f46",
    },
  },
  {
    month: 1,
    chapter: "Chapter – 2 · Consistency",
    quote: "Success is the product of daily habits, not once-in-a-lifetime transformations.",
    author: "James Clear",
    message: "Consistency compounds quietly. Win the ordinary days and greatness follows.",
    gradient: "linear-gradient(135deg, #fdf2f8, #fbcfe8)",
    colors: {
      chapter: "#9d174d",
      quote: "#831843",
      author: "#be185d",
      message: "#9d174d",
    },
  },
  {
    month: 2,
    chapter: "Chapter – 3 · Execution",
    quote: "Ideas are easy. Execution is everything.",
    author: "Tony Robbins",
    message: "Stop overthinking. Action creates clarity and momentum.",
    gradient: "linear-gradient(135deg, #f5f3ff, #ddd6fe)",
    colors: {
      chapter: "#4c1d95",
      quote: "#5b21b6",
      author: "#6d28d9",
      message: "#4c1d95",
    },
  },
  {
    month: 3,
    chapter: "Chapter – 4 · Focus",
    quote: "The successful warrior is the average man with laser-like focus.",
    author: "Bruce Lee",
    message: "Eliminate distractions. Depth beats speed.",
    gradient: "linear-gradient(135deg, #f0fdfa, #99f6e4)",
    colors: {
      chapter: "#115e59",
      quote: "#134e4a",
      author: "#0f766e",
      message: "#115e59",
    },
  },
  {
    month: 4,
    chapter: "Chapter – 5 · Growth",
    quote: "Without continual growth and progress, such words as improvement have no meaning.",
    author: "Benjamin Franklin",
    message: "Growth requires discomfort. Lean into resistance.",
    gradient: "linear-gradient(135deg, #fefce8, #fef08a)",
    colors: {
      chapter: "#854d0e",
      quote: "#713f12",
      author: "#a16207",
      message: "#854d0e",
    },
  },
  {
    month: 5,
    chapter: "Chapter – 6 · Power of Routine",
    quote: "Motivation gets you going, but discipline keeps you growing.",
    author: "John C. Maxwell",
    message: "Routines remove decision fatigue. Systems create freedom.",
    gradient: "linear-gradient(135deg, #fdf4ff, #f3e8ff)",
    colors: {
      chapter: "#6b21a8",
      quote: "#581c87",
      author: "#7e22ce",
      message: "#6b21a8",
    },
  },
  {
    month: 6,
    chapter: "Chapter – 7 · Resilience",
    quote: "Do not pray for an easy life, pray for the strength to endure a difficult one.",
    author: "Bruce Lee",
    message: "Every setback is training. Stay unbreakable.",
    gradient: "linear-gradient(135deg, #fff7ed, #fed7aa)",
    colors: {
      chapter: "#9a3412",
      quote: "#7c2d12",
      author: "#c2410c",
      message: "#9a3412",
    },
  },
  {
    month: 7,
    chapter: "Chapter – 8 · Money & Value",
    quote: "Formal education will make you a living; self-education will make you a fortune.",
    author: "Jim Rohn",
    message: "Invest in skills. Value creation precedes income.",
    gradient: "linear-gradient(135deg, #ecfeff, #cffafe)",
    colors: {
      chapter: "#155e75",
      quote: "#164e63",
      author: "#0891b2",
      message: "#155e75",
    },
  },
  {
    month: 8,
    chapter: "Chapter – 9 · Mastery",
    quote: "The man who loves walking will walk further than the man who loves the destination.",
    author: "Naval Ravikant",
    message: "Fall in love with the process, not the outcome.",
    gradient: "linear-gradient(135deg, #f8fafc, #e2e8f0)",
    colors: {
      chapter: "#0f172a",
      quote: "#020617",
      author: "#334155",
      message: "#0f172a",
    },
  },
  {
    month: 9,
    chapter: "Chapter – 10 · Leadership",
    quote: "A leader is one who knows the way, goes the way, and shows the way.",
    author: "John C. Maxwell",
    message: "Lead yourself first. Influence follows example.",
    gradient: "linear-gradient(135deg, #f0f9ff, #bae6fd)",
    colors: {
      chapter: "#075985",
      quote: "#0c4a6e",
      author: "#0284c7",
      message: "#075985",
    },
  },
  {
    month: 10,
    chapter: "Chapter – 11 · Patience",
    quote: "Great things are not done by impulse, but by a series of small things brought together.",
    author: "Vincent Van Gogh",
    message: "Patience is power. Time rewards persistence.",
    gradient: "linear-gradient(135deg, #faf5ff, #e9d5ff)",
    colors: {
      chapter: "#581c87",
      quote: "#4a044e",
      author: "#7e22ce",
      message: "#581c87",
    },
  },
  {
    month: 11,
    chapter: "Chapter – 12 · Legacy",
    quote: "What we do in life echoes in eternity.",
    author: "Marcus Aurelius",
    message: "Build habits that outlive motivation. Your future self is watching.",
    gradient: "linear-gradient(135deg, #ecfdf3, #bbf7d0)",
    colors: {
      chapter: "#14532d",
      quote: "#052e16",
      author: "#15803d",
      message: "#14532d",
    },
  },
];
